# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5a0cae9038533cb39b2871cd8f58a10ad5edb14f31b2f089fec870494859d670e037a38b55dcffb1403d031abb57ae32ea2c67a8c1a65c2a8bb817a950e8204

test:
  secret_key_base: 9db425a7d44d72029ade5f46cb7e106b450e9989705427e525c59820fc7ad56238d8b1a7aa18da437f5fae0345f5c3163e57765b48fbc2c9dff45198365be11c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
